### ISSUE TITLE
PgSQL 16 数据库初始化有异常，原因是system_user 

### ISSUE THREAD

**Issue by yYang365** [SenQi-666/fastapi-vue-admin#1]
PgSQL 16 数据库初始化有异常，原因是system_user 

参考：
[https://www.postgresql.org/docs/current/functions-info.html](https://www.postgresql.org/docs/current/functions-info.html)

> system_user → text

> Returns the authentication method and the identity (if any) that the user presented during the authentication cycle before they were assigned a database role. It is represented as auth_method:identity or NULL if the user has not been authenticated (for example if [Trust authentication](https://www.postgresql.org/docs/current/auth-trust.html) has been used).

建议将PgSQL版本推荐为15

**Comment by SenQi-666** [comment]
> PgSQL 16 数据库初始化有异常，之所以
> 
> 参考： https://www.postgresql.org/docs/current/functions-info.html
> 
> > 系统用户 → 文本
> 
> > 返回用户在被分配数据库角色之前的身份验证周期中提供的身份验证方法和身份（如果有）。如果用户尚未经过身份验证（例如，如果使用了[Trust 身份验证），则表示为 auth_method:identity 或 NULL。](https://www.postgresql.org/docs/current/auth-trust.html)
> 
> 建议将 PgSQL 版本推荐为 15

麻烦提供一下数据库初始化时详细的异常信息

**Comment by SenQi-666** [comment]
> PgSQL 16 数据库初始化有异常，原因是system_user
> 
> 参考： https://www.postgresql.org/docs/current/functions-info.html
> 
> > system_user → text
> 
> > Returns the authentication method and the identity (if any) that the user presented during the authentication cycle before they were assigned a database role. It is represented as auth_method:identity or NULL if the user has not been authenticated (for example if [Trust authentication](https://www.postgresql.org/docs/current/auth-trust.html) has been used).
> 
> 建议将PgSQL版本推荐为15

我这边使用的版本为14，并未出现初始化异常。麻烦提供一下数据库初始化时详细的异常信息。

**Comment by SenQi-666** [comment]
已推荐PgSQL版本为14。
